# SVR

This is Python code to fit SVR models on our time series data, and predict ahead!

## 1) First, we are getting our data and environment set up

In [25]:
print('hello and welcome to a functioning script')

hello and welcome to a functioning script

In [26]:
print('running')
import time
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit 
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
%matplotlib inline

os.chdir('/rds/general/user/ag1620/home/summerproj/results_data')
os.getcwd()

running

'/rds/general/user/ag1620/home/summerproj/results_data'

In [146]:
dataset_path = "short_1.csv"
df = pd.read_csv(dataset_path,header=0,index_col=0)

df['chunk'] =  pd.to_datetime(df['chunk'], format="%Y-%m-%d %H:%M:%S")
print(df.columns)
print(df.shape)

trainlength = df[df['traintest'].isin(range(0,1))].shape[0]
testlength = df[df['traintest'].isin(range(1,2))].shape[0]

## Choose your variables!
date_time = df['chunk']
df = df[['chunk','texts', 'localtime','weekday', 'tweet_avg', 'retweet_avg', 'likes_avg',
       'temp', 'clouds', 'covid_deaths', 'covid_announcements']]

## TRANSFORM YOUR VARIABLES!
df["texts"] = df["texts"].apply(lambda x: math.sqrt(x))
df["tweet_avg"] = df["tweet_avg"].apply(lambda x: math.log(x+0.1))
df["retweet_avg"] = df["retweet_avg"].apply(lambda x: math.log(x+0.1))
df["likes_avg"] = df["likes_avg"].apply(lambda x: math.log(x+0.1))
print("Updated DataFrame:")
df.head()

Index(['chunk', 'texts', 'localtime', 'weekday', 'school_hols',
       'exam_results_week', 'bank_holiday', 'temp', 'clouds', 'rainfall',
       'covid_cases', 'covid_deaths', 'covid_announcements', 'daily_temp',
       'tweet_avg', 'retweet_avg', 'likes_avg', 'traintest'],
      dtype='object')
(8043, 18)
Updated DataFrame:

,chunk,texts,localtime,weekday,tweet_avg,retweet_avg,likes_avg,temp,clouds,covid_deaths,covid_announcements
1,2020-03-01 00:00:00,8.062258,00:00:00,Sunday,-1.655958,-2.302585,-1.266493,5.29,40.0,0.0,0
2,2020-03-01 01:00:00,7.071068,01:00:00,Sunday,-1.655958,-2.302585,-1.266493,4.98,40.0,0.0,0
3,2020-03-01 02:00:00,7.071068,02:00:00,Sunday,-1.655958,-2.302585,-1.266493,4.96,40.0,0.0,0
4,2020-03-01 03:00:00,5.196152,03:00:00,Sunday,-1.655958,-2.302585,-1.266493,4.43,39.0,0.0,0
5,2020-03-01 04:00:00,4.472136,04:00:00,Sunday,-1.655958,-2.302585,-1.266493,4.35,46.0,0.0,0

In [147]:
# Splitting data into 
    # train
    # test

column_indices = {name: i for i, name in enumerate(df.columns)}

n = len(df)
train = df[:int(trainlength)]
test = df[trainlength:]

num_features = df.shape[1]

In [148]:
## Split Truth and Predictors for train
y_train = train['texts']
print(y_train.shape)
X_train = train[['localtime','weekday',
                 'tweet_avg', 'retweet_avg', 'likes_avg',
                 'temp','clouds',
                 'covid_deaths','covid_announcements'
                ]] #
print(X_train.shape)
y_test = test['texts']
print(y_test.shape)
X_test = test[['localtime','weekday',
                 'tweet_avg', 'retweet_avg', 'likes_avg',
                 'temp','clouds',
                 'covid_deaths','covid_announcements'
              ]]  #
print(X_test.shape)

(7887,)
(7887, 9)
(156,)
(156, 9)

In [149]:
# Creating dummy variables for categorical variables of local time and weekday
X_train = pd.get_dummies(X_train, columns=['localtime','weekday'])
X_test = pd.get_dummies(X_test, columns=['localtime','weekday'])
X_train

,tweet_avg,retweet_avg,likes_avg,temp,clouds,covid_deaths,covid_announcements,localtime_00:00:00,localtime_01:00:00,localtime_02:00:00,...,localtime_21:00:00,localtime_22:00:00,localtime_23:00:00,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday
1,-1.655958,-2.302585,-1.266493,5.29,40.0,0.0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,-1.655958,-2.302585,-1.266493,4.98,40.0,0.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,-1.655958,-2.302585,-1.266493,4.96,40.0,0.0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,-1.655958,-2.302585,-1.266493,4.43,39.0,0.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,-1.655958,-2.302585,-1.266493,4.35,46.0,0.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7883,0.095310,2.761735,0.972843,0.50,40.0,1164.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7884,0.498017,2.761735,1.432918,1.00,75.0,1164.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7885,0.651378,3.057853,1.611254,1.33,40.0,1164.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7886,0.651378,3.074795,1.574282,1.88,40.0,1164.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7887,0.824973,3.460324,1.574282,2.07,20.0,1164.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [150]:
print(X_train.shape)
print(X_test.shape)

(7887, 38)
(156, 38)

In [151]:
# Rescale the dataset
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
# Check data types
print("X_train:" + str(type(X_train)))
print(X_train.shape)
print("y_train:" + str(type(y_train)))
print(y_train.shape)
print("X_test:" + str(type(X_test)))
print(X_test.shape)
print("y_test:" + str(type(y_test)))
print(y_test.shape)
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

X_train:<class 'numpy.ndarray'>
(7887, 38)
y_train:<class 'pandas.core.series.Series'>
(7887,)
X_test:<class 'numpy.ndarray'>
(156, 38)
y_test:<class 'pandas.core.series.Series'>
(156,)

In [152]:
# This code kills performance - all predictors should be aligned
#time = train[['time']].reset_index(drop=True)
#X_train = pd.concat([time,X_train.iloc[:,1:]], axis=1,ignore_index=True)

In [153]:
#This code keeps only the weekday and local
#X_train = X_train.iloc[:,1:]
#X_test = X_test.iloc[:,1:]

In [154]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,-1.770917,-1.688254,-1.275283,-0.957114,-0.433308,-0.912296,-0.305187,4.792979,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,-0.406616,2.447861,-0.40852,-0.40852,-0.40852
1,-1.770917,-1.688254,-1.275283,-1.009708,-0.433308,-0.912296,-0.305187,-0.208639,4.792979,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,-0.406616,2.447861,-0.40852,-0.40852,-0.40852
2,-1.770917,-1.688254,-1.275283,-1.013101,-0.433308,-0.912296,-0.305187,-0.208639,-0.208639,4.792979,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,-0.406616,2.447861,-0.40852,-0.40852,-0.40852
3,-1.770917,-1.688254,-1.275283,-1.103020,-0.465733,-0.912296,-0.305187,-0.208639,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,-0.406616,2.447861,-0.40852,-0.40852,-0.40852
4,-1.770917,-1.688254,-1.275283,-1.116592,-0.238752,-0.912296,-0.305187,-0.208639,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,-0.406616,2.447861,-0.40852,-0.40852,-0.40852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7882,0.079826,0.877161,0.066448,-1.769774,-0.433308,2.537040,-0.305187,-0.208639,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,2.459321,-0.408520,-0.40852,-0.40852,-0.40852
7883,0.505406,0.877161,0.342109,-1.684945,0.701599,2.537040,-0.305187,-0.208639,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,2.459321,-0.408520,-0.40852,-0.40852,-0.40852
7884,0.667478,1.027165,0.448962,-1.628958,-0.433308,2.537040,-0.305187,-0.208639,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,2.459321,-0.408520,-0.40852,-0.40852,-0.40852
7885,0.667478,1.035747,0.426809,-1.535647,-0.433308,2.537040,-0.305187,-0.208639,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,2.459321,-0.408520,-0.40852,-0.40852,-0.40852
7886,0.850934,1.231043,0.426809,-1.503412,-1.081826,2.537040,-0.305187,-0.208639,-0.208639,-0.208639,...,-0.208307,-0.208307,-0.208307,-0.40852,-0.40852,2.459321,-0.408520,-0.40852,-0.40852,-0.40852

## 3) Fitting Models

In [155]:
## Fit regression model
#svr_rbf = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1)
#svr_lin = SVR(kernel='linear', C=100, gamma='auto')
#svr_poly = SVR(kernel='poly', C=100, gamma='auto', degree=3, epsilon=.1, coef0=1)

In [156]:
# Cross Validation 1
tss = TimeSeriesSplit(n_splits=4)
parameters = {'kernel': ['rbf'], # ,'linear','poly'
              'C': [1, 10, 100, 1000, 10000], # range(80,120,20), # Lower = More regularisation
              'gamma': [0.0001, 0.001, 0.01, 0.1], # 'scale','auto' # Lower = samples have larger radius of influence - "smoothness of the forecasting function"
              'epsilon': [0.01, 0.1, 1] } # 
gscv = GridSearchCV(SVR(), parameters, n_jobs=1, cv=tss) # scoring='neg_median_absolute_error' > this makes the predictions far worse

In [ ]:
# Default internal scoring strategy is R2
print('running')
#import time
t0 = time.time()

gscv.fit(X=X_train, y=y_train)
print(gscv.best_params_)
svr_model = gscv.best_estimator_

t1 = time.time()
total = t1-t0
print(total)

running

In [ ]:
#import time
t0 = time.time()

y_pred = svr_model.predict(X_test[:12]) ** 2
y_test = y_test[:12]
t1 = time.time()
total = t1-t0
print(total)

## 4) Assessing Performance

In [ ]:
# over what time would you like to assess error metrics?
days = 1
t=y_test[:days*12] ** 2
p=y_pred[:days*12]
times=test['chunk'][:days*12]

fig = plt.figure(figsize=(12,6))
plt.plot(times,t,color='b',label='True')
plt.plot(times,p,color='r',label='Preds')
plt.xlabel("Time")
plt.ylabel("Texts")
plt.legend()
plt.show()

In [ ]:
# ASSESS ERROR METRICS
import math
# Get error metrics
MAE = metrics.mean_absolute_error(t, p)
MSE = metrics.mean_squared_error(t, p)
RMSE = math.sqrt(MSE)
R2 = metrics.r2_score(t, p)
maxerror = metrics.max_error(t, p)
print(' MAE = {}\n MSE = {}\n RMSE = {}\n R2= {}\n max-error = {}'.format(MAE, MSE, RMSE, R2, maxerror))

In [ ]:
# training performance
y_trainpred = svr_model.predict(X_train) ** 2
y_traintruth = y_train ** 2
MAE = metrics.mean_absolute_error(y_traintruth, y_trainpred)
MSE = metrics.mean_squared_error(y_traintruth, y_trainpred)
RMSE = math.sqrt(MSE)
R2 = metrics.r2_score(y_traintruth, y_trainpred)
maxerror = metrics.max_error(y_traintruth, y_trainpred)
print(' MAE = {}\n MSE = {}\n RMSE = {}\n R2= {}\n max-error = {}'.format(MAE, MSE, RMSE, R2, maxerror))

## 5) Save Predictions

In [144]:
# save test set performance dataframe
testchunk = pd.DataFrame(test['chunk']).reset_index(drop=True)
ytest = pd.DataFrame(y_test).reset_index(drop=True) ** 2
ypred = pd.DataFrame(y_pred).reset_index(drop=True)
df_c = pd.concat([testchunk,ytest,ypred], axis=1)
df_c.columns = ['chunk','truth','preds']
df_c.head()
df_c.to_csv('super_short_6_SVR_preds.csv')

In [145]:
# save training set performance dataframe
trainchunk = pd.DataFrame(train['chunk']).reset_index(drop=True)
ytrain = pd.DataFrame(y_train).reset_index(drop=True)  ** 2
ytrainpred = pd.DataFrame(y_trainpred).reset_index(drop=True)
df_c = pd.concat([trainchunk,ytrain,ytrainpred], axis=1)
df_c.columns = ['chunk','truth','preds']
df_c.head()

                chunk  truth      preds
0 2021-03-28 00:00:00   87.0  88.628429
1 2021-03-28 01:00:00   62.0  49.596968
2 2021-03-28 02:00:00   36.0  34.927125
3 2021-03-28 03:00:00   24.0  27.134197
4 2021-03-28 04:00:00   22.0  13.616239